{{- if .Values.bnb_fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
annotations:
  {{- if .Values.extra.keepStorageAfterDelete }}
  helm.sh/resource-policy: keep
  {{- end }}
metadata:
  name: bnb-datadir
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bnb_fullnode.storage.size }}
{{- end }}