{{- if .Values.doge.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
annotations:
  {{- if .Values.extra.keepStorageAfterDelete }}
  helm.sh/resource-policy: keep
  {{- end }}
metadata:
  name: dogecoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.doge.storage.size }}
{{- end }}