{{- if .Values.btc_lightning.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightning-rtl
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.btc_lightning.rtl.storage.size }}
{{- end }}