{{- if or .Values.btc.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bitcoin-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
