{{- if .Values.btc_lightning.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightning-lnd
  namespace: {{ .Values.namespace }}
  labels:
    app: lightning-lnd
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lightning-lnd
  template:
    metadata:
      labels:
        app: lightning-lnd
    spec:
      containers:
      - name: lightning-lnd
        image:  {{ .Values.btc_lightning.lnd.image }}
        args:
        - --wallet-unlock-password-file=/root/.lnd/wallet-password
        - --externalip=$(EXTERNAL_IP):$(P2P_PORT)
        - --listen=0.0.0.0:$(P2P_PORT)
        - --restlisten=0.0.0.0:8080
        - --tlsextradomain=lightning-lnd-rest
        - --bitcoin.$(NETWORK)
        - --bitcoin.node=bitcoind
        - --bitcoind.rpchost=$(BITCOIND_RPCHOST)
        - --bitcoind.rpcuser=$(BITCOIND_RPCUSER)
        - --bitcoind.rpcpass=$(BITCOIND_RPCPASS)
        - --bitcoind.zmqpubrawblock=$(BITCOIND_ZMQPUBRAWBLOCK)
        - --bitcoind.zmqpubrawtx=$(BITCOIND_ZMQPUBRAWTX)
        env:
          - name: EXTERNAL_IP
            value: {{ .Values.external_ip }}
          - name: P2P_PORT
            value: {{ .Values.btc_lightning.lnd.p2p_port | quote }}
          - name: NETWORK
            value: {{ .Values.btc_lightning.network }}

          - name: BITCOIND_RPCUSER
          {{- if .Values.btc_lightning.lnd.BITCOIND_RPCUSER }}
            value: {{ .Values.btc_lightning.lnd.BITCOIND_RPCUSER }}
          {{- else }}
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: username
                optional: false
          {{- end }}

          - name: BITCOIND_RPCPASS
          {{- if .Values.btc_lightning.lnd.BITCOIND_RPCPASS }}
            value: {{ .Values.btc_lightning.lnd.BITCOIND_RPCPASS }}
          {{- else }}
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: password
                optional: false
          {{- end }}
          - name: BITCOIND_RPCHOST
            value: {{ .Values.btc_lightning.lnd.BITCOIND_RPCHOST }}
          - name: BITCOIND_ZMQPUBRAWBLOCK
            value: {{ .Values.btc_lightning.lnd.BITCOIND_ZMQPUBRAWBLOCK }}
          - name: BITCOIND_ZMQPUBRAWTX
            value: {{ .Values.btc_lightning.lnd.BITCOIND_ZMQPUBRAWTX }}
          {{- range $name, $value := .Values.btc_lightning.lnd.extraEnv }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.btc_lightning.lnd.p2p_port }}
          name: p2p
        - containerPort: 8080
          name: rest
        volumeMounts:
        - name: lightning-lnd
          mountPath: /root/.lnd
      volumes:
      - name: lightning-lnd
        persistentVolumeClaim:
          claimName: lightning-lnd
{{- end }}
