{{- if or .Values.trx.enabled .Values.usdt.enabled .Values.usdc.enabled}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tron-shkeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: tron-shkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tron-shkeeper
  template:
    metadata:
      labels:
        app: tron-shkeeper
    spec:
      {{- with .Values.dev.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:

      - name: app
        image: {{ .Values.tron_shkeeper.image }}
        command:
        - gunicorn
        - --access-logfile=-
        - --workers=1
        - --threads=64
        - --timeout=600
        - --bind=0.0.0.0:6000
        - run:server
        ports:
        - containerPort: 6000
          name: http
        volumeMounts:
        - name: data
          mountPath: /app/data
        env:
          - name: BTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: username
          - name: BTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: password
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
          - name: SHKEEPER_HOST
            value: "shkeeper:5000"
          - name: FULLNODE_URL
            value: {{ .Values.tron_fullnode.url }}
          {{- if .Values.tron_shkeeper.multiserver_config_json }}
          - name: MULTISERVER_CONFIG_JSON
            value: {{ .Values.tron_shkeeper.multiserver_config_json | toJson | quote }}
          {{- end }}
          {{- if .Values.tron_shkeeper.external_drain_config }}
          - name: EXTERNAL_DRAIN_CONFIG
            value: {{ .Values.tron_shkeeper.external_drain_config | toJson | quote }}
          {{- end }}
          {{- range $name, $value := .Values.tron_shkeeper.extraEnv }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          # - name: MULTISERVER_REFRESH_BEST_SERVER_PERIOD
          #   value: {{ .Values.tron_shkeeper.multiserver_refresh_best_server_period | default "" | quote }}
          - name: DB_URI
            value: mysql+pymysql://root:shkeeper@mariadb/shkeeper?charset=utf8mb4

      - name: tasks
        image: {{ .Values.tron_shkeeper.image }}
        command: ["celery", "-A", "celery_worker.celery", "worker", "--loglevel=info", "-B", "--schedule=/app/data/celerybeat-schedule"]
        volumeMounts:
        - name: data
          mountPath: /app/data
        env:
          - name: BTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: username
          - name: BTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: password
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
          - name: SHKEEPER_HOST
            value: "shkeeper:5000"
          - name: FULLNODE_URL
            value: {{ .Values.tron_fullnode.url }}
          - name: C_FORCE_ROOT
            value: "1"
          {{- if .Values.tron_shkeeper.multiserver_config_json }}
          - name: MULTISERVER_CONFIG_JSON
            value: {{ .Values.tron_shkeeper.multiserver_config_json | toJson | quote }}
          {{- end }}
          {{- if .Values.tron_shkeeper.external_drain_config }}
          - name: EXTERNAL_DRAIN_CONFIG
            value: {{ .Values.tron_shkeeper.external_drain_config | toJson | quote }}
          {{- end }}
          {{- range $name, $value := .Values.tron_shkeeper.extraEnv }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          # - name: MULTISERVER_REFRESH_BEST_SERVER_PERIOD
          #   value: {{ .Values.tron_shkeeper.multiserver_refresh_best_server_period | default "" | quote }}
          - name: DB_URI
            value: mysql+pymysql://root:shkeeper@mariadb/shkeeper?charset=utf8mb4

      - name: redis
        image: redis:7
        command: ["redis-server", "--loglevel", "warning",  "--bind",  "0.0.0.0", "--protected-mode", "no", "--appendonly", "yes", "--shutdown-on-sigint", "save", "--shutdown-on-sigterm", "save"]
        volumeMounts:
        - name: redis-data
          mountPath: /data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tron-shkeeper-data
      - name: redis-data
        persistentVolumeClaim:
          claimName: tron-shkeeper-redis-data
{{- end }}
