CREATE DATABASE IF NOT EXISTS `shkeeper`;
CREATE DATABASE IF NOT EXISTS `ethereum-shkeeper`;
CREATE DATABASE IF NOT EXISTS `bnb-shkeeper`;
CREATE DATABASE IF NOT EXISTS `xrp-shkeeper`;
CREATE DATABASE IF NOT EXISTS `polygon-shkeeper`;
CREATE DATABASE IF NOT EXISTS `avalanche-shkeeper`;
