{{- if .Values.btc_fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-fullnode
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
{{- end }}
