{{ if .Values.btc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: jsonrpc
    port: 8332
    protocol: TCP
    targetPort: 8332
  - name: zmq-pub-rawblock
    port: 28334
    targetPort: 28334
  - name: zmq-pub-rawtx
    port: 28335
    targetPort: 28335
  - name: zmq-pub-hashblock
    port: 28336
    targetPort: 28336
  - name: nginx
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: bitcoind
{{ end }}