{{- if .Values.monero.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-wallet-rpc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monero.storage.size }}
{{- end }}